import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import LogoutButton from "@/components/LogoutButton";
import Link from "next/link";
import ToasterComponent from "@/components/Toaster";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToasterComponent />
        <main className="min-h-screen">
          <Navbar />
          <div className="">{children}</div>
        </main>
      </body>
    </html>
  );
}
